### ISSUE TITLE
Exception while testing modifyAcl

### ISSUE THREAD

**Issue by praneethh** [procter-gamble-oss/octopufs#3]
I downloaded the jar and installed in the cluster. Below are the steps I followed to test modifyAcl

Step1:
 ```
spark.sparkContext.hadoopConfiguration.set("fs.azure.account.auth.type.xxxx.dfs.core.windows.net", "OAuth")
spark.sparkContext.hadoopConfiguration.set("fs.azure.account.oauth.provider.type.xxxx.dfs.core.windows.net",  "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider")
spark.sparkContext.hadoopConfiguration.set("fs.azure.account.oauth2.client.id.xxxx.dfs.core.windows.net", "xxxxx")
spark.sparkContext.hadoopConfiguration.set("fs.azure.account.oauth2.client.secret.xxxx.dfs.core.windows.net", "xxxx)
spark.sparkContext.hadoopConfiguration.set("fs.azure.account.oauth2.client.endpoint.xxx.dfs.core.windows.net", "https://login.microsoftonline.com/xxxx/oauth2/token")
```

Step2:
```
import com.pg.bigdata.octopufs.acl.AclManager
implicit val conf = spark.sparkContext.hadoopConfiguration
```

Step3:

```
val acl = AclManager.FsPermission("user","rw-","ACCESS","pran")
AclManager.modifyAcl(Array("abfss://xxx@xxxx.dfs.core.windows.net/ww_dl_playground/str_fill/recvd_dt=2019-10-01"),acl)
```

I'm getting the below exception

```
Modifying ACLs - attempt 0
ACL entry: user:pran:rw-
java.lang.Exception: Some paths failed - showing 10 of them abfss://xxx@xxxx.dfs.core.windows.net/ww_dl_playground/str_fill/recvd_dt=2019-10-01

	at com.pg.bigdata.octopufs.acl.AclManager$.modifyAcl(AclManager.scala:70)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4328446028965452:1)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4328446028965452:57)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4328446028965452:59)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4328446028965452:61)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-4328446028965452:63)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-4328446028965452:65)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw$$iw$$iw.<init>(command-4328446028965452:67)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw$$iw.<init>(command-4328446028965452:69)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw$$iw.<init>(command-4328446028965452:71)
	at line9883ec2a2f6648da901d8c174e25171059.$read$$iw.<init>(command-4328446028965452:73)
	at line9883ec2a2f6648da901d8c174e25171059.$read.<init>(command-4328446028965452:75)
	at line9883ec2a2f6648da901d8c174e25171059.$read$.<init>(command-4328446028965452:79)
	at line9883ec2a2f6648da901d8c174e25171059.$read$.<clinit>(command-4328446028965452)
	at line9883ec2a2f6648da901d8c174e25171059.$eval$.$print$lzycompute(<notebook>:7)
	at line9883ec2a2f6648da901d8c174e25171059.$eval$.$print(<notebook>:6)
	at line9883ec2a2f6648da901d8c174e25171059.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:699)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:652)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:202)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:385)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$9.apply(DriverLocal.scala:362)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:251)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:246)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:49)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:288)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:49)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:362)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JacekTokar** [comment]
First of all, sorry for late reply - I was not getting any notifications from the repo...
Looking into it...

**Comment by JacekTokar** [comment]
Ok, the problem is apparently with the authentication method. ACLs cannot be set using service principal authentication. Can you try using storage key and see if it works?

**Comment by praneethh** [comment]
Thanks for the reply. I tried by using storage key but still getting the same error.

**Comment by JacekTokar** [comment]
Such error occurs ONLY if provided path does not exist (I assume you triple-checked) or if cluster does not have sufficient privileges. Try putting spark.hadoop. in front of parameter names in hadoop conf: 

```spark.hadoop.fs.azure.account.key.<storage-account-name>.blob.core.windows.net <storage-account-access-key>```

Remember that octopus requires different security settings than dataframe api.

Hope this helps

**Comment by JacekTokar** [comment]
Any luck?

**Comment by praneethh** [comment]
Getting the same error, not sure what is causing the issue. I believe it has something to do with the cluster permissions.

**Comment by JacekTokar** [comment]
Do other functions work? For example, can you run getSize(path) from fs package?

**Comment by JacekTokar** [comment]
Please reopen the issue if problem still occurs
