### ISSUE TITLE
file copy is not working

### ISSUE THREAD

**Issue by csmurthy** [procter-gamble-oss/octopufs#6]
import com.pg.bigdata.octopufs.fs.DistributedExecution

spark.conf.set("spark.speculation","false")
implicit val s = spark
DistributedExecution.copyFolder("abfss://container@adlsname.dfs.core.windows.net/j/IRI","abfss://container@adlsname.dfs.core.windows.net/j/IRI2")
--- This code is giving below exception

org.apache.spark.SparkException: Job aborted due to stage failure: Task 4 in stage 1.0 failed 4 times, most recent failure: Lost task 4.3 in stage 1.0 (TID 53, 10.139.64.4, executor 0): java.io.IOException: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.spark.util.GlobalHadoopConfiguration.<init>()
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1514)
	at org.apache.spark.SerializableWritable.readObject(SerializableWritable.scala:41)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2235)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2126)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1625)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:465)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:423)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$9.apply(TorrentBroadcast.scala:336)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:337)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1$$anonfun$apply$1$$anonfun$apply$3.apply(TorrentBroadcast.scala:257)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1$$anonfun$apply$1.apply(TorrentBroadcast.scala:233)
	at org.apache.spark.util.KeyLock.withLock(KeyLock.scala:64)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:228)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1507)

***** Scala 2.11 , spark 2.4.5********

got different exception on - scala 2.12 , spark 3.0.0

org.apache.spark.sql.AnalysisException: Cannot modify the value of a Spark config: spark.speculation;
	at org.apache.spark.sql.RuntimeConfig.requireNonStaticConf(RuntimeConfig.scala:155)
	at org.apache.spark.sql.RuntimeConfig.set(RuntimeConfig.scala:43)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-3131419051375577:2)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-3131419051375577:51)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read$$iw$$iw$$iw$$iw.<init>(command-3131419051375577:53)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read$$iw$$iw$$iw.<init>(command-3131419051375577:55)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read$$iw$$iw.<init>(command-3131419051375577:57)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read$$iw.<init>(command-3131419051375577:59)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read.<init>(command-3131419051375577:61)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read$.<init>(command-3131419051375577:65)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$read$.<clinit>(command-3131419051375577)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$eval$.$print$lzycompute(<notebook>:7)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$eval$.$print(<notebook>:6)
	at line1702ab1726aa40ffb8a34c5056a2c4a627.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)

**Comment by JacekTokar** [comment]
Hi, Octopufs has not been tested on spark3 yet, but the only thing that may require slight change is what you've found here - spark does not allow changes of some settings compaing to spark 2. If are you using databricks or other spark distribution?

**Comment by csmurthy** [comment]
Thanks for the quick response . I am using Azure Databricks. How to fix  this in ADB

**Comment by JacekTokar** [comment]
Ok, so you can either use 2.4 spark or later (but before 3.0.0). Make sure you pick the right release jar from releases in github. Hopefully I named them in a way you'll know which one to use for which runtime :)

**Comment by csmurthy** [comment]
I took the latest release .
Runtime 6.4 (Scala 2.11, Spark 2.4.5) , getting the same exception.

org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 1.0 failed 4 times, most recent failure: Lost task 9.3 in stage 1.0 (TID 54, 10.139.64.4, executor 0): java.io.IOException: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.spark.util.GlobalHadoopConfiguration.<init>()
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1514)
	at org.apache.spark.SerializableWritable.readObject(SerializableWritable.scala:41)
	at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2235)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2126)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1625)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:465)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:423)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$9.apply(TorrentBroadcast.scala:336)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.broadcast.TorrentBroadcast$.unBlockifyObject(TorrentBroadcast.scala:337)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1$$anonfun$apply$1$$anonfun$apply$3.apply(TorrentBroadcast.scala:257)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1$$anonfun$apply$1.apply(TorrentBroadcast.scala:233)
	at org.apache.spark.util.KeyLock.withLock(KeyLock.scala:64)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:228)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1507)

**Comment by JacekTokar** [comment]
I just tested https://github.com/procter-gamble-tech/octopufs/releases/tag/1.0.2_2.11_dbr6.4 on runtime 6.6 and it worked perfectly fine. Please check

**Comment by csmurthy** [comment]
Thanks for looking into this. I am still getting the same error while copying the folder or individual files
Rest of the scenario  like ACL setting , Size , Move and delete files are working

**Comment by JacekTokar** [comment]
Copy distributes the load to spark tasks and, unfortunately, Databricks mixed into 2.4.x releases parts of spark 3.0.x and as of some version I had to change the way how I send configuration to the tasks.
I am surprised that it didn't work for you. Could you create cluster from scratch with runtime 6.6 and reupload the jar to the cluster and check again? I went that route last time and it copied the folder without any issue

**Comment by csmurthy** [comment]
Thanks @JacekTokar , I followed the mentioned steps, but I am getting the same error.

**Comment by JacekTokar** [comment]
@csmurthy That's really weird... I will try to prepare spark 3.0.0 version this/next week. Hopefully this will work for you (still don't understand how this version doesn't...)

**Comment by flvndh** [comment]
If it can help, I encountered the same error trying to move data between two mounted ADLS Gen 1 instances. I used DBR 6.4 and OctopuFS 1.0.2_2.11. DBR 6.6 did not solve the problem for me as well. Installing version 1.0.2_2.11_dbr6.4 and restarting the cluster solved it.

**Comment by csmurthy** [comment]
Hi @JacekTokar - Did you get a chance to check this

**Comment by JacekTokar** [comment]
Hi, sorry for late reply. It's been busy few weeks... Anyway, please let me know you exact setup you want this to work with, I mean: dbr runtime version and storage account type. I will make sure I will test on exactly same configuration you require, because, as I previously stated, jars from github releases did work for me on multiple 6.x versions, so let's be very specific.
I will be waiting for your info

**Comment by csmurthy** [comment]
Thank you @JacekTokar .
I tried on 6.6/7.3/7.4 runtimes . ADLS Gen2
![image](https://user-images.githubusercontent.com/33412636/101880929-b2d19400-3bb9-11eb-94f5-15b9cdb6db2f.png)

**Comment by JacekTokar** [comment]
Hi,

Sorry it took so long. I just released version 1.1 for spark 3 and scala 2.12. I have tested it on Runtime 7.3 LTS and it worked without any problem.
https://github.com/procter-gamble-tech/octopufs/releases/tag/1.1

Hope this fixes your issue.

Sorry it took so long

**Comment by csmurthy** [comment]
Thank you! I'll check and update you

**Comment by JacekTokar** [comment]
Hey, Happy New Year!

Any update?

**Comment by csmurthy** [comment]
Thanks @JacekTokar . it is working

**Comment by JacekTokar** [comment]
Cool. Closing the issue then
